### ISSUE TITLE
The rows appears but the data is missing

### ISSUE THREAD

**Issue by joedayz** [gregturn/react-and-spring-data-rest#4]
Hi Greg.

I followed the guide step by step and the result is similar to the source code (basic). The table appears , the rows according to the number of records entered in DatabaseLoader but the data is missing.

I am attaching this picture.

Joe
![1](https://cloud.githubusercontent.com/assets/1118135/10178509/e47486bc-66c5-11e5-82aa-dec60da7cf79.png)

**Comment by gregturn** [comment]
@joedayz Thanks, but I can't see any image.

**Comment by joedayz** [comment]
OK I updated the post. 

Joe

**Comment by gregturn** [comment]
Here is one definite possibility. I'm assuming you ran `./mvnw spring-boot:run`. On first run, it pulls down all the JS modules from the npm repository. That repo has been known to be flakey. If not all the modules made it, you might be missing something critical.

Can you peek at your browser's console and see if it's complaining about anything?

If this is the case, the "real" solution is to do another `./mvnw clean spring-boot:run` until it pulls down all the npm stuff successfully. Good thing is you only have to do this once.

**Comment by joedayz** [comment]
Ok. I am executing the project from STS and my OS is Windows.

Check this line in mvnw.bat

100 if exist "%M2_HOME%\bin\mvn.bat" goto init  --> must to be  .bat and not .cmd

I am executing now  c:/> mvnw clean spring-boot:run  , I think that some library of npm is missing too.

I will confirm after that.

Joe

**Comment by gregturn** [comment]
Okay, I haven't tested this on Windows. If you have maven installed, you can fall back to regular maven. I haven't verified mvnw on Windows.

**Comment by joedayz** [comment]
Greg, it runs perfect now!!!

Thanks for  your support.

Joe

**Comment by gregturn** [comment]
No problem. Happy react coding.
