### ISSUE TITLE
TypeError: employeeCollection.entity._links.profile is undefined

### ISSUE THREAD

**Issue by muks2048** [gregturn/react-and-spring-data-rest#8]
Hi Greg, thanks for the awesome blog about react and Spring Data REST, however I'm getting a javascript error when I try to run the second tutorial about Hypermedia, and the table does not display any record when rendered in the browser. The error message says:
 TypeError: employeeCollection.entity._links.profile is undefined
 Kindly help me overcome this, so I can continue to the rest of the tutorials.
 Thanks in advance!

**Comment by muks2048** [comment]
I was able to run the first tutorial (React.js and Spring Data REST: Part 1 - Basic Features), only after pinning down React to version 0.13.3, just as chanwook suggested.

**Comment by gregturn** [comment]
Great. There is a general plan for me to convert this series into a tutorial. At the same time, I'm going to make some updates, like migrating to ES6 and the latest version of react. This will all include moving from require.js to webpack. All these things should help pin the version of react, and make it more stable. Fixing any one of these by themselves isn't quite worth the effort.

**Comment by muks2048** [comment]
Thanks, let me patiently wait until then!
